name: nixpkgs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # At 00:00 on Sunday
env:
  NIX_VERSION: '2.19.2'
jobs:
  update-nixpkgs:
    permissions:
      contents: write
      pull-requests: write
    if: github.ref == 'refs/heads/main' && github.repository == 'cri-o/cri-o'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          install_url: https://releases.nixos.org/nix/nix-${{ env.NIX_VERSION }}/install
      - run: make nixpkgs
      - name: Check workspace
        id: create_pr
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            echo "create_pr=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Create PR if required
        uses: peter-evans/create-pull-request@v6
        if: ${{ steps.create_pr.outputs.create_pr == 'true' }}
        with:
          commit-message: Update nixpkgs
          title: 'Update nixpkgs'
          body: Update nixpkgs to the latest HEAD commit.
          labels: kind/ci, release-note-none, ok-to-test
          branch: nixpkgs
          delete-branch: true
          signoff: true
