name: nixpkgs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # At 00:00 on Sunday
env:
  NIX_VERSION: "2.24.3"
permissions:
  contents: read

jobs:
  update-nixpkgs:
    permissions:
      contents: write
      pull-requests: write
    if: github.ref == 'refs/heads/main' && github.repository == 'cri-o/cri-o'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: cachix/install-nix-action@3715ab1a11cac9e991980d7b4a28d80c7ebdd8f9 # v27
        with:
          install_url: https://releases.nixos.org/nix/nix-${{ env.NIX_VERSION }}/install
      - run: make nixpkgs
      - name: Check workspace
        id: create_pr
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            echo "create_pr=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Create PR if required
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
        if: ${{ steps.create_pr.outputs.create_pr == 'true' }}
        with:
          commit-message: Update nixpkgs
          title: "Update nixpkgs"
          body: Update nixpkgs to the latest HEAD commit.
          labels: kind/ci, release-note-none, ok-to-test
          branch: nixpkgs
          delete-branch: true
          signoff: true
