name: verify
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # must be specified without patch version
          version: v1.32

          # Only show new issues for a pull request.
          only-new-issues: true

  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: lumaxis/shellcheck-problem-matchers@v1
    - name: shellcheck
      run: make shellcheck

  shfmt:
    name: shfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: shfmt
      run: make shfmt

  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: validate-docs
      run: make docs-validation

  gendocs:
    name: gendocs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt update && sudo apt install libselinux1-dev
    - name: validate generated docs
      run: |
        make docs-generation
        ./hack/tree_status.sh

  completions:
    name: completions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: validate-completions
      run: |
        make completions
        ./hack/tree_status.sh

  vendor:
    name: vendor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: cache go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}
          restore-keys: go-
      - name: vendor
        run: make check-vendor
